### PR TITLE
Update CKK.cs

### PR DESCRIPTION
**Pull request by alexyack**
GOST R 34.10-2012 512 bit key

### CODE REVIEW

**Comment by jariq** [comment]
Thanks for the PR but could you please provide more info where did you get the value for `CKK_GOSTR3410_512` constant? AFAIK it is not present in any of the official PKCS#11 specifications nor [draft git repository](https://github.com/czimman/pkcs11/).

**Comment by alexyack** [comment]
First part of this constant is [here](https://github.com/AktivCo/RutokenPkcs11Interop/blob/6c9a18a7b298b04f00a564fefe72600e55ec7011/src/RutokenPkcs11Interop/Common/Extended_CKM.cs#L7-L8)
Second part is [here](
https://github.com/AktivCo/RutokenPkcs11Interop/blob/6c9a18a7b298b04f00a564fefe72600e55ec7011/src/RutokenPkcs11Interop/Common/Extended_CKK.cs#L8)

**Comment by alexyack** [comment]
I have just pushed the same modifications to Pkcs11Admin. 
Check them too, please.

**Comment by jariq** [comment]
Those are vendor specific extensions and as such are not suitable for inclusion in the base Pkcs11Interop library. If you need to use them then you can define them in your application code or you can use [Aktiv.RutokenPkcs11Interop](https://www.nuget.org/packages/Aktiv.RutokenPkcs11Interop/) library.

**Comment by alexyack** [comment]
This is an one example in C# that I can find for a short time.
This "vendor specific" extensions is Russian national standard fro new crypto algorithms - rutoken is one of examples.  
There are also exist two vendors that share the same key identifiers - ESMART and Aladdin R.D.  
I am attaching draft of PKCS#11 extension dated by 2013. Sorry I can find only an Russian language text, but the constant values are readable.
[Расширение PKCS#11 для использования российских стандартов ГОСТ Р 34.10-2012 и ГОСТ Р 34.11-2012.pdf](https://github.com/Pkcs11Interop/Pkcs11Interop/files/3111002/PKCS.11.34.10-2012.34.11-2012.pdf)

**Comment by alexyack** [comment]
There are example by [ESMART](https://esmart.ru/upload/iblock/765/v6.P11_RusExt_12.pdf).

**Comment by alexyack** [comment]
Aladdin's SDK is not public, so I can not provide evidences of using this constants by this vendor.

**Pull request closed without merging**
